name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  get_it: ^8.2.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
