name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  get_it: ^8.2.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.5

flutter:
  uses-material-design: true
